// cap drop categories, territories, and constituents of other countries

cap drop if country == "World"
cap drop if country == "Advanced Economies"
cap drop if country == "Africa Eastern and Southern"
cap drop if country == "Africa Western and Central"
cap drop if country == "Arab World"
cap drop if country == "British Virgin Islands"
cap drop if country == "Channel Islands"
cap drop if country == "Caribbean small states"
cap drop if country == "Central Europe and the Baltics"
cap drop if country == "Curacao"
cap drop if country == "Early-demographic dividend"
cap drop if country == "East Asia & Pacific"
cap drop if country == "East Asia & Pacific (IDA & IBRD countries)"
cap drop if country == "East Asia & Pacific (excluding high income)"
cap drop if country == "Emerging Market and Developing Economies"
cap drop if country == "Euro area"
cap drop if country == "Europe & Central Asia"
cap drop if country == "Europe & Central Asia (IDA & IBRD countries)"
cap drop if country == "Europe & Central Asia (excluding high income)"
cap drop if country == "European Union"
cap drop if country == "Fragile and conflict affected situations"
cap drop if country == "Faroe Islands"
cap drop if country == "French Polynesia"
cap drop if country == "Gibraltar"
cap drop if country == "Global Partnership for Education"
cap drop if country == "Greenland"
cap drop if country == "Guam"
cap drop if country == "Heavily indebted poor countries (HIPC)"
cap drop if country == "High income"
cap drop if country == "Hong Kong SAR, China"
cap drop if country == "IBRD only"
cap drop if country == "IDA & IBRD total"
cap drop if country == "IDA blend"
cap drop if country == "IDA only"
cap drop if country == "IDA total"
cap drop if country == "Isle of Man"
cap drop if country == "Late-demographic dividend"
cap drop if country == "Latin America & Caribbean"
cap drop if country == "Latin America & Caribbean (excluding high income)"
cap drop if country == "Latin America & the Caribbean (IDA & IBRD countries)"
cap drop if country == "Least developed countries: UN classification"
cap drop if country == "Lending category not classified"
cap drop if country == "Low & middle income"
cap drop if country == "Low income"
cap drop if country == "Lower middle income"
cap drop if country == "Macao SAR, China"
cap drop if country == "Marshall Islands"
cap drop if country == "Mayotte"
cap drop if country == "Middle East & North Africa"
cap drop if country == "Middle East & North Africa (IDA & IBRD countries)"
cap drop if country == "Middle East & North Africa (excluding high income)"
cap drop if country == "Middle income"
cap drop if country == "Netherlands Antilles"
cap drop if country == "New Caledonia"
cap drop if country == "North America"
cap drop if country == "Northern Mariana Islands"
cap drop if country == "Not classified"
cap drop if country == "OECD members"
cap drop if country == "Other small states"
cap drop if country == "Pacific island small states"
cap drop if country == "Post-demographic dividend"
cap drop if country == "Pre-demographic dividend"
cap drop if country == "Sint Maarten (Dutch part)"
cap drop if country == "Small states"
cap drop if country == "South Asia"
cap drop if country == "South Asia (IDA & IBRD)"
cap drop if country == "St. Martin (French part)"
cap drop if country == "Sub-Saharan Africa"
cap drop if country == "Sub-Saharan Africa (IDA & IBRD countries)"
cap drop if country == "Sub-Saharan Africa (excluding high income)"
cap drop if country == "Tokelau"
cap drop if country == "Turks and Caicos Islands"
cap drop if country == "Upper middle income"
cap drop if country == "Virgin Islands (U.S.)"
